In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [5]:
iris = load_iris()


In [7]:
iris.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 

In [9]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [13]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


Logistic Regression

In [15]:
l_scores = cross_val_score(LogisticRegression(max_iter = 1000), iris.data, iris.target)

In [16]:
l_scores

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [17]:
np.average(l_scores)

np.float64(0.9733333333333334)

Decision Tree

In [18]:
d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)

In [19]:
d_scores

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [20]:
np.average(d_scores)

np.float64(0.9666666666666668)

Support Vector Machine

In [21]:
s_scores = cross_val_score(SVC(), iris.data, iris.target)

In [22]:
s_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [23]:
np.average(s_scores)

np.float64(0.9666666666666666)

Random Forest

In [24]:
r_scores = cross_val_score(RandomForestClassifier(n_estimators = 40), iris.data, iris.target)

In [25]:
r_scores

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [26]:
np.average(r_scores)

np.float64(0.9666666666666668)